### ISSUE TITLE
Broken installation on Ubuntu 18.04.2 LTS

### ISSUE THREAD

**Issue by lneuhaus** [CEMES-CNRS/PyMoDAQ#12]
I followed the instructions here http://pymodaq.cnrs.fr/usage/Installation.html.After experiencing problems on my host machine, I tried it in a docker container, but ran into trouble again. 

Here is the sequence of commands I used:
```
docker run -i -t continuumio/miniconda3 /bin/bash
# in the docker container bash
conda create -n pymodaq
conda activate pymodaq
conda install pip
conda install pyqt
pip install pymodaq==1.6.0
```
Everything works until the last command. The output I get is:
```
(pymodaq) root@3fd3f68c914a:/# pip install pymodaq==1.6.0
Collecting pymodaq==1.6.0
  Downloading https://files.pythonhosted.org/packages/87/9b/69b5e7e85d6d2ac49470df31eb6a6b6f8ad3192a8edc32e71e1fff3decb9/pymodaq-1.6.0-py3-none-any.whl (4.0MB)
     |████████████████████████████████| 4.0MB 2.9MB/s 
Collecting numba (from pymodaq==1.6.0)
  Downloading https://files.pythonhosted.org/packages/b5/9b/7ad0a181b66d58334a2233f18fc8345e3ff17ea6f8db0eb59dc31182b6a9/numba-0.45.1-cp37-cp37m-manylinux1_x86_64.whl (3.5MB)
     |████████████████████████████████| 3.5MB 6.8MB/s 
Collecting scipy (from pymodaq==1.6.0)
  Downloading https://files.pythonhosted.org/packages/94/7f/b535ec711cbcc3246abea4385d17e1b325d4c3404dd86f15fc4f3dba1dbb/scipy-1.3.1-cp37-cp37m-manylinux1_x86_64.whl (25.2MB)
     |████████████████████████████████| 25.2MB 6.2MB/s 
Collecting dask (from pymodaq==1.6.0)
  Downloading https://files.pythonhosted.org/packages/fe/33/4b606b0cc2166760141f5576a1851e4e1d0e9b44f736bf185c01bb993dab/dask-2.5.0-py3-none-any.whl (759kB)
     |████████████████████████████████| 768kB 7.4MB/s 
Collecting pyqt5 (from pymodaq==1.6.0)
  Downloading https://files.pythonhosted.org/packages/12/63/a7a32557fdce42b1ddf2353d9e2a576143376046ead0b1918fd4cfe01b90/PyQt5-5.13.1-5.13.1-cp35.cp36.cp37.cp38-abi3-manylinux1_x86_64.whl (62.1MB)
     |████████████████████████████████| 62.2MB 6.4MB/s 
Collecting bitstring (from pymodaq==1.6.0)
  Downloading https://files.pythonhosted.org/packages/c7/b9/ce7458b35633968eae3477a201a00f6c8e01cab0ccb200ea5099d41dd977/bitstring-3.1.6-py3-none-any.whl
Collecting numpy (from pymodaq==1.6.0)
  Downloading https://files.pythonhosted.org/packages/ba/e0/46e2f0540370f2661b044647fa447fef2ecbcc8f7cdb4329ca2feb03fb23/numpy-1.17.2-cp37-cp37m-manylinux1_x86_64.whl (20.3MB)
     |████████████████████████████████| 20.3MB 5.4MB/s 
Collecting tables (from pymodaq==1.6.0)
  Downloading https://files.pythonhosted.org/packages/d5/5e/0463e9a2ae44838e36ca81dfe8a6e056b15cc15be77e7f8feae116f02ec7/tables-3.5.2-cp37-cp37m-manylinux1_x86_64.whl (4.3MB)
     |████████████████████████████████| 4.3MB 7.1MB/s 
Collecting pymodaq-pid-models (from pymodaq==1.6.0)
  Downloading https://files.pythonhosted.org/packages/1f/67/ce4d2cf7a778b6b5d5d38990cb7d7e33444c44b766c2d7d22b4d4abe3f2d/pymodaq_pid_models-0.0.1-py3-none-any.whl
Collecting easydict (from pymodaq==1.6.0)
  Downloading https://files.pythonhosted.org/packages/4c/c5/5757886c4f538c1b3f95f6745499a24bffa389a805dee92d093e2d9ba7db/easydict-1.9.tar.gz
Collecting pymodaq-plugins>=1.2.0 (from pymodaq==1.6.0)
  Downloading https://files.pythonhosted.org/packages/5e/74/c5752b10eef56e7bb61a27306a2d7c413378248cce62ec1a91fe5873887c/pymodaq_plugins-1.2.0-py3-none-any.whl (13.0MB)
     |████████████████████████████████| 13.0MB 6.1MB/s 
Collecting simple-pid (from pymodaq==1.6.0)
  Downloading https://files.pythonhosted.org/packages/7c/d4/ebea9ab299514526bd6c5529f277d4f3233f25bd8fb2931dbbe26b72dd1c/simple_pid-0.2.3-py2.py3-none-any.whl
Collecting pyqtgraph==0.10 (from pymodaq==1.6.0)
  Downloading https://files.pythonhosted.org/packages/cd/ad/307e0280df5c19986c4206d138ec3a8954afc722cea991f4adb4a16337d9/pyqtgraph-0.10.0.tar.gz (1.5MB)
     |████████████████████████████████| 1.6MB 7.6MB/s 
Collecting llvmlite>=0.29.0dev0 (from numba->pymodaq==1.6.0)
  Downloading https://files.pythonhosted.org/packages/30/ae/a33eb9a94734889c189ba4b05170ac0ede05904db5d3dd31158cb33ac16e/llvmlite-0.29.0-1-cp37-cp37m-manylinux1_x86_64.whl (20.2MB)
     |████████████████████████████████| 20.2MB 5.4MB/s 
Collecting PyQt5_sip<13,>=4.19.19 (from pyqt5->pymodaq==1.6.0)
  Downloading https://files.pythonhosted.org/packages/bf/63/d363b567237375235d270049fd6416c83949f470bb51539458966cd7a38c/PyQt5_sip-4.19.19-cp37-cp37m-manylinux1_x86_64.whl (67kB)
     |████████████████████████████████| 71kB 7.6MB/s 
Collecting mock>=2.0 (from tables->pymodaq==1.6.0)
  Downloading https://files.pythonhosted.org/packages/05/d2/f94e68be6b17f46d2c353564da56e6fb89ef09faeeff3313a046cb810ca9/mock-3.0.5-py2.py3-none-any.whl
Collecting numexpr>=2.6.2 (from tables->pymodaq==1.6.0)
  Downloading https://files.pythonhosted.org/packages/2c/69/274c2b81b9bdf7783150461c8982f23248dc917402ed4c6f8aa4b90bb98e/numexpr-2.7.0-cp37-cp37m-manylinux1_x86_64.whl (162kB)
     |████████████████████████████████| 163kB 7.1MB/s 
Collecting six>=1.9.0 (from tables->pymodaq==1.6.0)
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting phconvert (from pymodaq-plugins>=1.2.0->pymodaq==1.6.0)
  Downloading https://files.pythonhosted.org/packages/56/e1/f06dacdfe910c9f3a7e43e66e8f1f406b65c277e181581efd8097ba2acbc/phconvert-0.8.2.tar.gz (64kB)
     |████████████████████████████████| 71kB 13.0MB/s 
Collecting harvesters (from pymodaq-plugins>=1.2.0->pymodaq==1.6.0)
  Downloading https://files.pythonhosted.org/packages/4f/38/861278e363975c62ec38896ac0ce4eddc64f3c3f87ea5e88772c08ff8cd8/harvesters-0.2.12-py3-none-any.whl (80kB)
     |████████████████████████████████| 81kB 7.8MB/s 
Collecting serial (from pymodaq-plugins>=1.2.0->pymodaq==1.6.0)
  Downloading https://files.pythonhosted.org/packages/1f/51/6a260c498162c37d0759f3759b7647a10d8d30caba1cfc9aa4b5b1f0d08b/serial-0.0.97-py2.py3-none-any.whl (40kB)
     |████████████████████████████████| 40kB 10.7MB/s 
Collecting pyDAQmx (from pymodaq-plugins>=1.2.0->pymodaq==1.6.0)
  Downloading https://files.pythonhosted.org/packages/f8/c1/ea50dfc3f6c955d0d889563215e36e2db9808eabbe41c48292ac73f3153f/PyDAQmx-1.4.2.tar.gz
Collecting opencv-python (from pymodaq-plugins>=1.2.0->pymodaq==1.6.0)
  Downloading https://files.pythonhosted.org/packages/44/35/6db0fa2e644922533ddc2a3c41d1a86dabefce89d9db85ec31dcc69dc2e3/opencv_python-4.1.1.26-cp37-cp37m-manylinux1_x86_64.whl (28.7MB)
     |████████████████████████████████| 28.7MB 5.6MB/s 
Collecting pillow (from pymodaq-plugins>=1.2.0->pymodaq==1.6.0)
  Downloading https://files.pythonhosted.org/packages/a4/da/2bd281c875686230eabc13d20ab590ea617563b0e746abfb0698c4d5b645/Pillow-6.1.0-cp37-cp37m-manylinux1_x86_64.whl (2.1MB)
     |████████████████████████████████| 2.1MB 7.4MB/s 
Collecting pythonnet (from pymodaq-plugins>=1.2.0->pymodaq==1.6.0)
  Downloading https://files.pythonhosted.org/packages/4a/0a/5964a5a1fdf207fab8e718edd1f8d3578e0681577fe9abe0d9006f9718c2/pythonnet-2.4.0.tar.gz (1.8MB)
     |████████████████████████████████| 1.9MB 7.3MB/s 
Collecting pyvisa (from pymodaq-plugins>=1.2.0->pymodaq==1.6.0)
  Downloading https://files.pythonhosted.org/packages/51/d1/fc21b45228718cde06b33b08761a6a9aa859dfe51dfbf07e81e0f209e776/PyVISA-1.10.1.tar.gz (6.8MB)
     |████████████████████████████████| 6.8MB 6.3MB/s 
Requirement already satisfied: setuptools in /opt/conda/envs/pymodaq/lib/python3.7/site-packages (from phconvert->pymodaq-plugins>=1.2.0->pymodaq==1.6.0) (41.2.0)
Collecting future (from phconvert->pymodaq-plugins>=1.2.0->pymodaq==1.6.0)
  Downloading https://files.pythonhosted.org/packages/90/52/e20466b85000a181e1e144fd8305caf2cf475e2f9674e797b222f8105f5f/future-0.17.1.tar.gz (829kB)
     |████████████████████████████████| 829kB 7.3MB/s 
Collecting genicam2 (from harvesters->pymodaq-plugins>=1.2.0->pymodaq==1.6.0)
  Downloading https://files.pythonhosted.org/packages/ab/15/dbb6c054914977ba6d9ea8ec31695b861e0f554cb83429476643555762b6/genicam2-0.0.0.dev5472-py3-none-manylinux1_x86_64.whl (3.0MB)
     |████████████████████████████████| 3.0MB 7.8MB/s 
Collecting iso8601>=0.1.12 (from serial->pymodaq-plugins>=1.2.0->pymodaq==1.6.0)
  Downloading https://files.pythonhosted.org/packages/ef/57/7162609dab394d38bbc7077b7ba0a6f10fb09d8b7701ea56fa1edc0c4345/iso8601-0.1.12-py2.py3-none-any.whl
Collecting pyyaml>=3.13 (from serial->pymodaq-plugins>=1.2.0->pymodaq==1.6.0)
  Downloading https://files.pythonhosted.org/packages/e3/e8/b3212641ee2718d556df0f23f78de8303f068fe29cdaa7a91018849582fe/PyYAML-5.1.2.tar.gz (265kB)
     |████████████████████████████████| 266kB 7.1MB/s 
Building wheels for collected packages: easydict, pyqtgraph, phconvert, pyDAQmx, pythonnet, pyvisa, future, pyyaml
  Building wheel for easydict (setup.py) ... done
  Created wheel for easydict: filename=easydict-1.9-cp37-none-any.whl size=6350 sha256=41aee2e58d24a8e1687176f45e6471ad982b9e3739a52aac681aa22513a8d7f3
  Stored in directory: /root/.cache/pip/wheels/9a/88/ec/085d92753646b0eda1b7df49c7afe51a6ecc496556d3012e2e
  Building wheel for pyqtgraph (setup.py) ... done
  Created wheel for pyqtgraph: filename=pyqtgraph-0.10.0-cp37-none-any.whl size=735677 sha256=8a3d07c96764ebebbd5c40cc7c1d379ee45373ca8c5d8d1c4314929e60ea19cf
  Stored in directory: /root/.cache/pip/wheels/93/a2/de/184ecdefdb91d760706d02389015dfa3b96e927eb1c42ace37
  Building wheel for phconvert (setup.py) ... done
  Created wheel for phconvert: filename=phconvert-0.8.2-cp37-none-any.whl size=53055 sha256=55838bc6ef13666961320e37de0beabf9f09cc9e81048fccd9a76da56aebbf24
  Stored in directory: /root/.cache/pip/wheels/ff/e8/4b/27e850b4c886160852e4b548cfd13574ea805c3bc2f0b4cf9a
  Building wheel for pyDAQmx (setup.py) ... done
  Created wheel for pyDAQmx: filename=PyDAQmx-1.4.2-cp37-none-any.whl size=21008 sha256=2ad04ca69ac366ac580813bb49347d3f7a76d52e36d36967dac863a666f04fb1
  Stored in directory: /root/.cache/pip/wheels/c0/6e/70/3b10e4f5b1ae1628d8d5106ed233561828c4b0933026bc5966
  Building wheel for pythonnet (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /opt/conda/envs/pymodaq/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-i5i77xsk/pythonnet/setup.py'"'"'; __file__='"'"'/tmp/pip-install-i5i77xsk/pythonnet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-lk1f17px --python-tag cp37
       cwd: /tmp/pip-install-i5i77xsk/pythonnet/
  Complete output (43 lines):
  running bdist_wheel
  running build
  running build_ext
  /bin/sh: 1: mono: not found
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-i5i77xsk/pythonnet/setup.py", line 658, in <module>
      zip_safe=False,
    File "/opt/conda/envs/pymodaq/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/opt/conda/envs/pymodaq/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/opt/conda/envs/pymodaq/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/opt/conda/envs/pymodaq/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-i5i77xsk/pythonnet/setup.py", line 610, in run
      return bdist_wheel.bdist_wheel.run(self)
    File "/opt/conda/envs/pymodaq/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/opt/conda/envs/pymodaq/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/conda/envs/pymodaq/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/opt/conda/envs/pymodaq/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/opt/conda/envs/pymodaq/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/conda/envs/pymodaq/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/opt/conda/envs/pymodaq/lib/python3.7/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/opt/conda/envs/pymodaq/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "/opt/conda/envs/pymodaq/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "/tmp/pip-install-i5i77xsk/pythonnet/setup.py", line 245, in build_extension
      self._install_packages()
    File "/tmp/pip-install-i5i77xsk/pythonnet/setup.py", line 424, in _install_packages
      subprocess.check_call(cmd, shell=use_shell)
    File "/opt/conda/envs/pymodaq/lib/python3.7/subprocess.py", line 347, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'mono tools/nuget/nuget.exe update -self' returned non-zero exit status 127.
  ----------------------------------------
  ERROR: Failed building wheel for pythonnet
  Running setup.py clean for pythonnet
  Building wheel for pyvisa (setup.py) ... done
  Created wheel for pyvisa: filename=PyVISA-1.10.1-cp37-none-any.whl size=128337 sha256=93f49dcba62b7e7be71fd45d7c26fe983f2953b299687477b5425918e638580e
  Stored in directory: /root/.cache/pip/wheels/51/8e/f2/dd4ebd8ea7a44c4520caa35fe6d6a74be065a8a94ab6380f29
  Building wheel for future (setup.py) ... done
  Created wheel for future: filename=future-0.17.1-cp37-none-any.whl size=488730 sha256=d011c2c40636608680ec8bd8f47df0bf2c61e0a36ba6c4dab59fb0ca075b6bdf
  Stored in directory: /root/.cache/pip/wheels/0c/61/d2/d6b7317325828fbb39ee6ad559dbe4664d0896da4721bf379e
  Building wheel for pyyaml (setup.py) ... done
  Created wheel for pyyaml: filename=PyYAML-5.1.2-cp37-cp37m-linux_x86_64.whl size=44103 sha256=9993a8389d387d0bf029bc84c240a62fa8f1f6a745f1b84dd8b9ab305cf312a0
  Stored in directory: /root/.cache/pip/wheels/d9/45/dd/65f0b38450c47cf7e5312883deb97d065e030c5cca0a365030
Successfully built easydict pyqtgraph phconvert pyDAQmx pyvisa future pyyaml
Failed to build pythonnet
Installing collected packages: numpy, llvmlite, numba, scipy, dask, PyQt5-sip, pyqt5, bitstring, six, mock, numexpr, tables, pymodaq-pid-models, easydict, future, phconvert, genicam2, harvesters, iso8601, pyyaml, serial, pyDAQmx, opencv-python, pillow, pythonnet, pyvisa, pymodaq-plugins, simple-pid, pyqtgraph, pymodaq
  Running setup.py install for pythonnet ... error
    ERROR: Command errored out with exit status 1:
     command: /opt/conda/envs/pymodaq/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-i5i77xsk/pythonnet/setup.py'"'"'; __file__='"'"'/tmp/pip-install-i5i77xsk/pythonnet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-xitp_x8v/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-install-i5i77xsk/pythonnet/
    Complete output (6 lines):
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help
    
    error: option --single-version-externally-managed not recognized
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/conda/envs/pymodaq/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-i5i77xsk/pythonnet/setup.py'"'"'; __file__='"'"'/tmp/pip-install-i5i77xsk/pythonnet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-xitp_x8v/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
(pymodaq) root@3fd3f68c914a:/# 

```

**Comment by lneuhaus** [comment]
Is pymodaq only supported for windows?

**Comment by seb5g** [comment]
My bad, I added a requirement in the setup of pymodaq_plugins that is only available on windows: pythonnet! I corrected the setup and applied a new version of pymodaq_plugins on pypi. Please try it again.

**Comment by lneuhaus** [comment]
Thanks. That fixes it. I got another error related to `DAQ_Measurement_main.py`, having to rename that file to lowercase letters. Please rename it so linux users wont suffer more than they have to :)

**Comment by seb5g** [comment]
Where did you get this error (related to DAQ_Measurement_main) because I think it is already lowercase, but maybe I forgot some code somewhere?
