### ISSUE TITLE
Cannot define a preset with only detectors or only actuators

### ISSUE THREAD

**Issue by quantumm** [CEMES-CNRS/PyMoDAQ#62]
Hi !
While doing some tests I defined a preset file with only actuators. At loading the program is frozen and I get the following error in the log:
2021-08-31 12:21:14,520 - pymodaq.dashboard - ERROR - 'Parameter Detectors has no child named params'
Traceback (most recent call last):
  File "c:\users\dbrestea\anaconda3\envs\pymodaq_330\lib\site-packages\pyqtgraph\parametertree\Parameter.py", line 681, in child
    param = self.names[names[0]]
KeyError: 'params'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\dbrestea\anaconda3\envs\pymodaq_330\lib\site-packages\pymodaq\dashboard.py", line 990, in set_preset_mode
    move_modules, detector_modules = self.set_file_preset(filename)
  File "c:\users\dbrestea\anaconda3\envs\pymodaq_330\lib\site-packages\pymodaq\dashboard.py", line 593, in set_file_preset
    plug['ID'] = plug['value'].child('params', 'main_settings', 'controller_ID').value()
  File "c:\users\dbrestea\anaconda3\envs\pymodaq_330\lib\site-packages\pyqtgraph\parametertree\Parameter.py", line 683, in child
    raise KeyError("Parameter %s has no child named %s" % (self.name(), names[0]))
KeyError: 'Parameter Detectors has no child named params'

So I tried also with only detectors and I get this one:

2021-08-31 12:37:16,998 - pymodaq.dashboard - ERROR - 'Parameter Moves has no child named params'
Traceback (most recent call last):
  File "c:\users\dbrestea\anaconda3\envs\pymodaq_330\lib\site-packages\pyqtgraph\parametertree\Parameter.py", line 681, in child
    param = self.names[names[0]]
KeyError: 'params'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\dbrestea\anaconda3\envs\pymodaq_330\lib\site-packages\pymodaq\dashboard.py", line 990, in set_preset_mode
    move_modules, detector_modules = self.set_file_preset(filename)
  File "c:\users\dbrestea\anaconda3\envs\pymodaq_330\lib\site-packages\pymodaq\dashboard.py", line 593, in set_file_preset
    plug['ID'] = plug['value'].child('params', 'main_settings', 'controller_ID').value()
  File "c:\users\dbrestea\anaconda3\envs\pymodaq_330\lib\site-packages\pyqtgraph\parametertree\Parameter.py", line 683, in child
    raise KeyError("Parameter %s has no child named %s" % (self.name(), names[0]))
KeyError: 'Parameter Moves has no child named params'

But if there is at least one detector and one actuator it works fine.

I guess it is just that this case has not been considered. But it could be quite common that a user wants to use such a preset. For example to have an interface with multiple cameras or multiple motors.

Ciao ;)

**Comment by seb5g** [comment]
is it still an issue?

**Comment by LMSC-NTappy** [comment]
Just faced the same problem today with an up-to-date installation from source

**Comment by seb5g** [comment]
Ok I'll work on it!


Le lun. 4 avr. 2022 à 17:12, Nicolas Tappy ***@***.***> a
écrit :

**Comment by seb5g** [comment]
Hello,
new patch release fix this issue see release https://github.com/CEMES-CNRS/PyMoDAQ/tree/3.5.6
Thanks to test it and close the issue if satisfied!

**Comment by LMSC-NTappy** [comment]
Thanks a lot!

I'll test it out a bit later this week, I need a fresh installation anyways

**Comment by LMSC-NTappy** [comment]
Now it works for me!

Cheers

Nico

**Comment by quantumm** [comment]
I tested it on my side it is working ;)

I close the issue.
