### ISSUE TITLE
AttributeError: 'WindowsPath' object has no attribute 'rstrip'

### ISSUE THREAD

**Issue by rgeneaux** [CEMES-CNRS/PyMoDAQ#69]
On two windows computer, python 3.8, updating to the latest pymodaq version throws an error when launching dashboard (AttributeError: 'WindowsPath' object has no attribute 'rstrip'). 

Edit : I thought updating to setuptools>60.0.0 fixed it but it looks like it doesn't always work. Will do more testing to figure it out. 
This issue can be deleted for now.

**Comment by seb5g** [comment]
I think this issue is related to an error between usage of a path as a WindowsPath (see pathlib package) (for which rstrip is nto available) and a path as a string (for which rstrip is available). Could you print the details of the log to see where the issue comes from?

**Comment by rgeneaux** [comment]
Sure! With pymodaq==3.5.2, launching dashboard :

Traceback (most recent call last):
  File "c:\miniconda\envs\manip\lib\site-packages\pkg_resources\__init__.py", line 2191, in _handle_ns
    loader = importer.find_spec(packageName).loader
  File "<frozen importlib._bootstrap_external>", line 1391, in find_spec
  File "<frozen importlib._bootstrap_external>", line 59, in _path_join
  File "<frozen importlib._bootstrap_external>", line 59, in <listcomp>
AttributeError: 'WindowsPath' object has no attribute 'rstrip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\miniconda\envs\manip\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\miniconda\envs\manip\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Miniconda\envs\manip\Scripts\dashboard.exe\__main__.py", line 4, in <module>
  File "c:\miniconda\envs\manip\lib\site-packages\pymodaq\dashboard.py", line 40, in <module>
    from pymodaq_plugin_manager.manager import PluginManager
  File "c:\miniconda\envs\manip\lib\site-packages\pymodaq_plugin_manager\manager.py", line 9, in <module>
    from pymodaq_plugin_manager.validate import validate_json_plugin_list, get_plugins, get_plugin, get_check_repo,\
  File "c:\miniconda\envs\manip\lib\site-packages\pymodaq_plugin_manager\validate.py", line 6, in <module>
    import pkg_resources
  File "c:\miniconda\envs\manip\lib\site-packages\pkg_resources\__init__.py", line 3238, in <module>
    @_call_aside
  File "c:\miniconda\envs\manip\lib\site-packages\pkg_resources\__init__.py", line 3222, in _call_aside
    f(*args, **kwargs)
  File "c:\miniconda\envs\manip\lib\site-packages\pkg_resources\__init__.py", line 3266, in _initialize_master_working_set
    for dist in working_set
  File "c:\miniconda\envs\manip\lib\site-packages\pkg_resources\__init__.py", line 3266, in <genexpr>
    for dist in working_set
  File "c:\miniconda\envs\manip\lib\site-packages\pkg_resources\__init__.py", line 2780, in activate
    declare_namespace(pkg)
  File "c:\miniconda\envs\manip\lib\site-packages\pkg_resources\__init__.py", line 2279, in declare_namespace
    _handle_ns(packageName, path_item)
  File "c:\miniconda\envs\manip\lib\site-packages\pkg_resources\__init__.py", line 2196, in _handle_ns
    loader = importer.find_module(packageName)
  File "<frozen importlib._bootstrap_external>", line 431, in _find_module_shim
  File "<frozen importlib._bootstrap_external>", line 1346, in find_loader
  File "<frozen importlib._bootstrap_external>", line 1391, in find_spec
  File "<frozen importlib._bootstrap_external>", line 59, in _path_join
  File "<frozen importlib._bootstrap_external>", line 59, in <listcomp>
AttributeError: 'WindowsPath' object has no attribute 'rstrip'

**Comment by seb5g** [comment]
related also wit #70 should be fine with requirement on setuptools version in 3.5.3 version of PyMoDAQ

**Comment by PhoebeLiu0109** [comment]
Hi, I was wondering whether you fixed the problem or not, cause I'm having the same problem:( How did you fix that eventually?
