### ISSUE TITLE
ImportError after installing pymodaq in a new environment.

### ISSUE THREAD

**Issue by LMSC-NTappy** [CEMES-CNRS/PyMoDAQ#70]
Hello @CEMES,

We are trying out PyMoDAQ for  controlling our PL/Raman setups and so far it looks just what we need! Thanks and congrats.

Thanks @seb5g for the nice videos on youtube as well!

I thought I would take the opportunity to signal a dependency issue with the current release. Starting from a new miniconda installation, I installed pymodaq with the following procedure:

-`conda create -n spectro_dev`
-`conda activate spectro_dev`
-`conda install python=3.9`
-`conda install scipy numpy matplotlib jupyter`
-`pip install pyqt5`
-`pip install pyside2`
-`pip install pymodaq`

Then, running `dashboard` throws:

```
(spectro_dev) C:\Users\admin>dashboard
Traceback (most recent call last):
  File "C:\Users\admin\.conda\envs\spectro_dev\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\admin\.conda\envs\spectro_dev\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\admin\.conda\envs\spectro_dev\Scripts\dashboard.exe\__main__.py", line 4, in <module>
  File "C:\Users\admin\.conda\envs\spectro_dev\lib\site-packages\pymodaq\dashboard.py", line 35, in <module>
    from pymodaq.daq_viewer.daq_viewer_main import DAQ_Viewer
  File "C:\Users\admin\.conda\envs\spectro_dev\lib\site-packages\pymodaq\daq_viewer\daq_viewer_main.py", line 23, in <module>
    from pymodaq.daq_utils.plotting.navigator import Navigator
  File "C:\Users\admin\.conda\envs\spectro_dev\lib\site-packages\pymodaq\daq_utils\plotting\navigator.py", line 7, in <module>
    import tables
  File "C:\Users\admin\.conda\envs\spectro_dev\lib\site-packages\tables\__init__.py", line 45, in <module>
    from .utilsextension import get_hdf5_version as _get_hdf5_version
ImportError: DLL load failed while importing utilsextension: The specified module could not be found.
```

Which I fixed by running 

-`conda install pytables`

After which it was still failing, but the error was different

```
(spectro_dev) C:\Users\admin>dashboard
Traceback (most recent call last):
  File "C:\Users\admin\.conda\envs\spectro_dev\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\admin\.conda\envs\spectro_dev\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\admin\.conda\envs\spectro_dev\Scripts\dashboard.exe\__main__.py", line 4, in <module>
  File "C:\Users\admin\.conda\envs\spectro_dev\lib\site-packages\pymodaq\dashboard.py", line 35, in <module>
    from pymodaq.daq_viewer.daq_viewer_main import DAQ_Viewer
  File "C:\Users\admin\.conda\envs\spectro_dev\lib\site-packages\pymodaq\daq_viewer\daq_viewer_main.py", line 23, in <module>
    from pymodaq.daq_utils.plotting.navigator import Navigator
  File "C:\Users\admin\.conda\envs\spectro_dev\lib\site-packages\pymodaq\daq_utils\plotting\navigator.py", line 7, in <module>
    import tables
  File "C:\Users\admin\.conda\envs\spectro_dev\lib\site-packages\tables\__init__.py", line 62, in <module>
    from .file import File, open_file, copy_file
  File "C:\Users\admin\.conda\envs\spectro_dev\lib\site-packages\tables\file.py", line 33, in <module>
    from . import hdf5extension
ImportError: DLL load failed while importing hdf5extension: The specified procedure could not be found.
```

Installing h5py using `conda install h5py` made everything work fine. 

Just posting this here because that should be an easy fix for you and also in case someone else encounters the same issue

Cheers and keep up the great work!

Nicolas

**Comment by quantumm** [comment]
Hello Nicolas,

Could it be that you installed python 3.9 ?
The recommended version is 3.8 : [http://pymodaq.cnrs.fr/en/latest/usage/Installation.html](http://pymodaq.cnrs.fr/en/latest/usage/Installation.html)

Good luck ;)

**Comment by LMSC-NTappy** [comment]
Indeed, however I was just able to replicate this issue with 3.8

I am able to fix it in the same way, though.

Cheers

**Comment by seb5g** [comment]
this issue seems to be coming from pytables but in fact comes from setuptools. I commited a patch on the github version last week. I'll publish right now a patch on pypi, check out the 3.5.3

**Comment by LMSC-NTappy** [comment]
still not working for me with 3.5.3, I still need to install pytables manually afterwards. 

It did uninstall `setuptools-58.0.4` and installed `setuptools 60.5.0` though

**Comment by seb5g** [comment]
my bad I thought it was the error I saw last week but it seems here it is indeed related only to pytables. I see you've installed manually pyside2. I don't think it is related but you have to choose between pyqt5 and pyside2 and actually there are still issues with pyside2 (so don't install it). Try that then export from you environment the list of packages and their version so I can try to reproduce your error...

**Comment by LMSC-NTappy** [comment]
I tried again without installing pyside2, and indeed the issue subsist.

Once again, I am able to solve it by installing manually pytables and h5py after pymodaq so no big deal.

Here is a package list

[tmplist.txt](https://github.com/CEMES-CNRS/PyMoDAQ/files/7929202/tmplist.txt)

Cheers

**Comment by quantumm** [comment]
I do reproduce this error indeed following:

`conda create -n pymodaq_353 python=3.8`
`conda activate pymodaq_353`
`pip install pyqt5`
`dashboard`

…and can solve it the same way!

**Comment by seb5g** [comment]
the error seems to come since the new version 3.7.0 from pytables has been published... using the 3.6.1 seems to be ok still.

This issue is tracked in :
https://github.com/PyTables/PyTables/issues/933

and can be solved with:
https://github.com/PyTables/PyTables/issues/933#issuecomment-1006658952

modifying the tables __init__ package

We can therefore do three things: 

1. let the user do the modification in the __init__ of pytables
2. force pymodaq install to use pytables 3.6.1(there is a binary up to python 3.8)
3. ask **python to be 3.9** as the standard install works there (i just tested it)

Could you also test this third solution guys and let me know if this work also for you?

**Comment by seb5g** [comment]
I think the best solution (tested just now) is to add some conditional installation on pytables as: 
```
    tables==3.6.1; python_version<"3.9"
    tables>=3.7.0; python_version>"3.8"
```
that makes pymodaq working with both version without any need of file modification by the user

**Comment by quantumm** [comment]
I just tested this:

`conda create -n pymodaq_353 python=3.9`
`conda activate pymodaq_353`
`pip install pymodaq`
`pip install pyqt5`
`dashboard`

There is still an error:

> Traceback (most recent call last):
  File "C:\Users\dbrestea\Anaconda3\envs\tmp_pymodaq_353\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\dbrestea\Anaconda3\envs\tmp_pymodaq_353\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\dbrestea\Anaconda3\envs\tmp_pymodaq_353\Scripts\dashboard.exe\__main__.py", line 4, in <module>
  File "C:\Users\dbrestea\Anaconda3\envs\tmp_pymodaq_353\lib\site-packages\pymodaq\dashboard.py", line 33, in <module>
    from pymodaq.daq_viewer.daq_viewer_main import DAQ_Viewer
  File "C:\Users\dbrestea\Anaconda3\envs\tmp_pymodaq_353\lib\site-packages\pymodaq\daq_viewer\daq_viewer_main.py", line 24, in <module>
    from pymodaq.daq_utils.plotting.navigator import Navigator
  File "C:\Users\dbrestea\Anaconda3\envs\tmp_pymodaq_353\lib\site-packages\pymodaq\daq_utils\plotting\navigator.py", line 8, in <module>
    import tables
  File "C:\Users\dbrestea\Anaconda3\envs\tmp_pymodaq_353\lib\site-packages\tables\__init__.py", line 45, in <module>
    from .utilsextension import get_hdf5_version as _get_hdf5_version
ImportError: DLL load failed while importing utilsextension: Le module spécifié est introuvable.

**Comment by seb5g** [comment]
can you try with pymodaq 3.5.4 ?

**Comment by quantumm** [comment]
I just tried this:

`conda create -n pymodaq_354 python=3.9`
`conda activate pymodaq_354`
`pip install pymodaq`
`pip install pyqt5`
`dashboard`

… but still the same error.

Actually I would have been surprised it work since with my previous attempt there was python 3.9 and pytables 3.7.0 installed.

I just remembered: we were using conda install pyqt5 before no? (rather than pip install pyqt5)

**Comment by quantumm** [comment]
Oups sorry I did not read the end of the instructions (remove cached packages). How do i do that?

**Comment by seb5g** [comment]
conda clean -e
conda clean -f

https://docs.conda.io/projects/conda/en/latest/commands/clean.html

**Comment by LMSC-NTappy** [comment]
Still does not work for me neither.

I tried 
conda create -n pmd_354
conda activate pmd_354
conda clean -a
conda install pip
conda install pymodaq==3.5.4
conda install pyqt5

Afterwards, still the same issue.

Here is the yml if you're interested

[pmd.txt](https://github.com/CEMES-CNRS/PyMoDAQ/files/8097139/pmd.txt)

**Comment by quantumm** [comment]
Yes!
I confirm it works for me too. I did not do conda clean.

`conda create -n pmd_354 python=3.8`
`conda activate pmd_354`
`pip install pymodaq`
`pip install pyqt5`

Be careful that the last two commands are done with **pip** and not conda.

**Comment by quantumm** [comment]
So in the end it seems like for python 3.8 if you force tables 3.6.1 it works.

But for python 3.9 it is still not working…

**Comment by seb5g** [comment]
there has been an new release of tables: 3.8.0. Do you think you could have a look?

**Comment by seb5g** [comment]
I didn't see the error happening again for a long time, do you agree guys? Can we just close the issue then?

**Comment by quantumm** [comment]
Yes I also think this can be closed.
